language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  hosts:
    - httpbin.org
elixir:
  - 1.5.2
otp_release:
  - 20.1.2
notifications:
  slack:
    rooms:
      - secure: "j6bC+QrahfmM8yh8YXaITJMJYX7XtvtE6T2vJLKU4nDrYMc02i8RHAeYD4bid91412DVMgBymYyKHs/5PVLBV5U7y465Uyu1F5cY+SDk1E8NfaY16l2lq3ptUIaOCxZRIC4pKg2CcR5/3pRuT+2j389iSTTMHNnncozTqDY2hLhCqx1agNpSMqtMVTq7ihZqm7dfq5BRR98RMT3Y8yfXY0rpk78gs7lMCCqEqXNysdQ4CaEE8r8syj2nHtAqf78JUIVgaItp257zRhgjEUOyRdA4Z197t4uoiOAeyXI6sChW5dlpDDLsxiXU6Dt3hVSjE+iud5MxbbeJimK9MhpCvnqK4W4B+LKItygmyEYW4eWdHrqA7GIjD4UfH5DCSKldHiOPtP8EnuQURxectHw9s3Ddx+wcxrObawBj7+hTGd04ZgBh6HdvJiJYW1ga/H6lQzbP9puxsArsUuWl2ZGdNjkg5W4O/0X3PFg/eL1T3QlBK4PLBcYzpfArp6af+iwQ3BBtQwOZ5F3WwFOD/DKqnJ7asbQfDUtBni0q8XE0KzqHg2eVfRye/c0NRE8h+20i+VqAyW3yqiZCKctCAbDcBOBRaSwxVZoKgUKhdHwGRrJcl0YMNBmgmQgNHqFO62FcBZrjxOBIZGpOHDgoQknaVXDxzNSyeRyh3pr3tl23Qoo="
    on_success: always
env:
  global:
    - Chart=gateway
    - MIX_ENV=test
    - REQUIRE_VERSION_TAGS="true"
    - TRUNK_BRANCH="master"
    # Docker Hub token
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - secure: "KCXY/H1KL3xUQJCLpE6M3rJBV2JI2Z9XzRv5PYP+iKSYntkx/m9EGVY+4UHKvzTU19Lq1I10V8Q5UsGkpbuPHeKdCeRF0F8BscQqmav85Q/NKPNSKKxq6SFyGVLr+lmER3BQkNEUMIQWWHo8chHrvwRZoAXSjDp8OXWt5nWr78hQXM3+lQZvy0OXB44bsAej4HR01vol2V3BR1by87SzLnJLjQRZbl9eWQ8L31/dvp7GHnj1Kle+dek4Kq1EOugfAnqJKSVuECbllHwF+f8kGN0ZI9XCrHxhcQF0tcAwisDbA9xrXQh/MiNbBA+YTIbktZV4477CE2oCBaULzptifZkUgC+004bxOTOrTBwx/nMuIBwhbn5TimDdH6yxLmipYnweO2G3PbE46ccfRnvl1zxpEsTm+GfOTMAT1Y8HKGNYdLO2c24BCdzd15sRA06HvbRJ1xJBAoRZxz8jY4gl/PF6zGAwzgAOR2EqAglifmm7rIj5vRy0v1Bf3FNLv2nKye4lurDQ5f/CZPoJLz5NkdLu1t+XT/7lT+tFftJu7EZEulaoIcCk38lIWToPBU/jMXcOiMlhOa72BpFptqvtf4W0x8cp60gyCz85aMHCn/q8TZDnMkEGTqBupEcp4c8Z9//LRFRKEh8RwbajxGO0CAXSnVY9jOzYnEGNlFMasOw="
    # GitHub token
    - secure: "oBqeNe/1qz5ognVswpex5VX3MWdBD0xPMYHiXQ8IU0lYooYvAR6WG4yG4UswysVzWv4SxKD/3SGpww8kYezmnx4wBbmKE7kwR+/uAFuP5y3S6QJ4ArBJwhu6XCq8UkQYZiyAwRztBcgey1WiJCuMt3JE8Pbx1J6BYPl+XO0orgGwPtCipLpF2fvqXHoWQYlKE06CRrmsTGakJOXhni5TmRVnRydt8a/4CdPbrQrGAaQ0l56KSXMHFMhKQ0KDTVRK3hlqk1zcjxSNhYhEgSLqU9TlG5MvtGOfbSLqqna8Feq+adjVvYYSqSfNDAcOCk8AWTUrOJgHbi48T6OWA1msf2LQ98nLsIDQuQgVp+2d0lK2PDaP5I6jcaeeKTsmvfsZ6YIs2r+Ulv5HW5Y9pqTd+pQNbjUaoS92zqRxNfq9vQ1jk3t9SXnHiHmsdqzw34fO2dnX3loPQuKw0zuRGmIBWw2AyYdvDolKmQveBm9BI/gphudU6iseEGO/BY9To3ocKwQSNVd5SDoQ5buv+h6jrMz3qHLAhCvaErbP+Kl0VRaLMcvHMjo+/mRXuvtTHNEXBeP0ZqCVUUeVrYvgysbMghACAi3wwS/Phadfnzsi5c2FXswz+gdBlW9tgagEMREzJDxxKLWdJo0yUg5ApJSsT+5KQj6dXLIDub83i2A3mL0="
  # Releases are generated automatically, stop infinite build loop
  except:
    - /^[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo /bin/bash ./bin/ci/init-db.sh
  # Run HTTPBin locally
  - docker pull citizenstig/httpbin:latest
  - docker run -d -p 80:8000 --name httpbin citizenstig/httpbin:latest
before_script:
  # Extract project name and version from mix.exs
  - source ./bin/ci/release/fetch-project-environment.sh
  # Load information about new version
  - source ./bin/ci/release/fetch-source-version.sh
  # Load information about changelog
  - source ./bin/ci/release/fetch-changelog.sh
script:
  # Check for versioning error
  - ./bin/ci/release/check-version-error.sh || travis_terminate 1
  # Increment version in mix.exs
  - ./bin/ci/release/put-source-version.sh || travis_terminate 1
  # Create release notes log for minor version
  - ./bin/ci/release/put-release-notes.sh
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
  # Build Docker container
  - ./bin/ci/release/build-container.sh || travis_terminate 1
  # Initialize DB for Docker container
  - source .env; PGPASSWORD="${DB_PASSWORD}"; psql -U ${DB_USER} -w -c"CREATE DATABASE ${DB_NAME}"
  # Run Docker container
  - sudo ./bin/ci/release/start-container.sh -a '--add-host=httpbin.org:$HOST_IP'
  - sudo ./bin/ci/release/check-container.sh || travis_terminate 1
  # Run acceptance tests on Docker container
  - ./test/sanity-test.sh || travis_terminate 1
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/release/push-changes.sh || travis_terminate 1
  - openssl aes-256-cbc -K $encrypted_05c49c11b097_key -iv $encrypted_05c49c11b097_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
  - sudo ./bin/deploy.sh || travis_terminate 1
after_success:
  # Rebuild docs
  - "mix docs --output docs"
