language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
  hosts:
    - httpbin.org
elixir:
  - 1.4.5
otp_release:
  - 20.0
env:
  global:
    - MIX_ENV=test
    - REQUIRE_VERSION_TAGS="true"
    - TRUNK_BRANCH="master"
    # Docker Hub token
    - DOCKER_HUB_ACCOUNT=nebo15
    - secure: "e7quIjgao/1Fc+tgjml23ogsbyxh35R+Vz4JDA5AA8PHLDyyogZdbl1GFVBMhio8SPzbWt+btW6LjNS0dHl6dxGnLZxCxTnyOgLUNBGNPKUmDj4T6YWSDmCy6c+RxErYzRzfLhhgQoLCpPDDPKkDeuHpCBocSUm0zpGTt9RQLydeiwmLaJtMu3/415HfD19PiY/TWvhOHHk1gpTXWD+1mUQLB/aOAgC1s9P11pcLLibjm6xr363fXoOSKp55e+8yI3lSN4UpH+ec5t1ubwDxrhOUrng/wNSxqwyLKG0Ovh2xUStpTPbVXnfx4AGm0KkpZcg90PpDeCvNPKGCzzspdrOvXD5IHTFqdUmqwQmHIlplF8PLu9AVV+9A3v86zndf/W8tGtBBolBqGKhCFr/ID0z3gN1K6YRQMK6rv1rVfrnmarma9Iy/wEn0qHk9hBYXxDcgM2RPdPmF7RTK4D4FvGNMRG6SFCd375ulaKkukIxjemKtjicpBggWZQP8YC7X95bptCG+1eDzNJdLnYE0jH3foX+19kM1bNCX+owKRkm9U+i2QfUNZPZS00aXXf9/1FT7fV1uMR+ZbC7uvxgc0ZKzyX5rauvs1qtHYR22dpgbUVXwZ91LSQizay9lWgGcz6B8JXYw/fteDPR97TLW/YPzvuOdGYzmyv58nlPttuY="
    # GitHub token
    - secure: "gmTS+DuyJ18k6kcWDOrzCFbBe05VZA5DzQqLzjnHYxNSZA+y4+vpIUH4xkN+JjEuYo2Jreg4Kz8NO0wP3gNROQrn3gYTdYXKQ8twJLsZ50IASnZQRLsDmuNIJsZcSgK8b27QNJYmfK3frDGlUubEws3POW3lo/uBfi4AzydoPhzo7HNNACMqFt7p1e5ndHaXmO2W3/DNkW/4NnpTA7SRcqMcykTIj7IzPOG+WVbGKxfUMuDCuabfMxeC5n5vROnbtoPoPrTR+7DPC/tKYnItwo4jvA08noMVrE7ziHrwyb7bPZs+ncfdwdS6LwIPwxGI7d+cUO9WOFdRzFH44xvY9lvRo3liMN800XZPJT6HFxf4GkQQuYW/trHjTYL7woHQmtwpGfBa1WFfDbSMSApk0YBUj0n0q0nMoV/9o7W8WIT0kjiCPbve0KUQYTHyqY5jcZS8hpZfno0+aVDTlq1jkEYdRb2wxBJXL/nDg5Z2reXsfEuAG4CTnzRkA8vv5otJXZrPmutNhHKg/+AdMsZAO5OsiCosqK9ouAypKoHhnYEigXD+kfMeWKpq4weDSfK6pYNoziMKYdsKKXnMg5/rWM9E3TpTUYgeiLFaHzgw7ll7fS8ra7jntC9Me2E5qqu3MjoEIErLE+k1IXw0EueQzX1BTVG2XqgUxTqYOIcuvYQ="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /^[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo /bin/bash ./bin/ci/init-db.sh
  # Run HTTPBin locally
  - docker pull citizenstig/httpbin:latest
  - docker run -d -p 80:8000 --name httpbin citizenstig/httpbin:latest
before_script:
  # Extract project name and version from mix.exs
  - source ./bin/ci/release/fetch-project-environment.sh
  # Load information about new version
  - source ./bin/ci/release/fetch-source-version.sh
  # Load information about changelog
  - source ./bin/ci/release/fetch-changelog.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/release/put-source-version.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo -a
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/ci/release/build-container.sh
  # Initialize DB for Docker container
  - source .env; PGPASSWORD="${DB_PASSWORD}"; psql -U ${DB_USER} -w -c"CREATE DATABASE ${DB_NAME}"
  # Run Docker container
  - sudo ./bin/ci/release/start-container.sh -a '--add-host=httpbin.org:$HOST_IP'
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "2" ]; then
      echo "[E] Container is not started\!";
      docker logs annon_api --details --since 5h;
      exit 1;
    fi;
  # Run acceptance tests on Docker container
  - ./test/sanity-test.sh
after_failure:
  - docker logs httpbin --details --since 5h
  - docker logs annon_api --details --since 5h
after_success:
  # Rebuild docs
  - "mix docs --output docs"
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/release/push-changes.sh
