language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
  hosts:
    - httpbin.org
elixir:
  - 1.4.5
otp_release:
  - 20.0
env:
  global:
    - MIX_ENV=test
    - REQUIRE_VERSION_TAGS="true"
    - TRUNK_BRANCH="master"
    # Docker Hub token
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - secure: "c/BJZ1aqM8NtrRCnK+Gi/tukm8nwk0Vdc8pkBDiB98wqu5ozlyzp+bXbEYzPL6ruNUgXk8Zzk3hErAmGkGKEoSt/dqi0Bd6hlrF2Xjp4kX4/bLOl+fUF01VT1CT9huX8dErqhAkNR9kvmtprnbgYsMMXwG5elLgqDR2A0TnWBtQuecIAYwDwseVsYuoeLBAO9eekF6slBOKqNO/8BtgqihmMrrY88lKn5HgOMGyKUQlNL7rDw1Hql6qlADHDNKgsl3rF5BwNNiap18yJLPD5rSVnR3xiF91D8CEh/oXAtJaoR67ufon6q5ggx5wfI/24l24OrW4kADmIAnxyR2kpZcxcDWYAtkExevM38eXADbuB9JdLg8YjC00a/4ofUzCxgSOxKZfDpr5cfwmsFrUTbMKtkypOdj6CM3P+rSZVFT8m9xd8cOjDYmXugU9O298HfPEQGZWraej8Xp5kBlsdzvgobWwBRbszc6+WJCh+nsRtNls6Jkh7oYNU/GUyvwjq12R/7JyIlksklssJH1mKvZd2OSa1Lcl4c9OoK3wyhokXILGyhVgPkaQXYNIWCD5xrvdZrtm1MON4RQN9T7Hk1fBv956WJyYDAXlmEQLREzRsB37mIODjD6RI4TpPve2KtCpi3m6lDgxRevwd/oPmhg2TtcQnLj7RVTJAB/jRnlg="
    # GitHub token
    - secure: "ky1IanGiJi8HV7fybwghJ0UGZJXU+wF0bYyO9n85LBPuF0X+68aRzRgoh8DTlXKEU/wdnR1wLQBlTcVCjMEeGZKSnF/5Lkt5190xpoRdPA8WBbmtWJB/f9gspryfMhKY81yMFHH3ECmuHps8d5nTMc3bMAfgjHKXU/W66vCruNHFlhFsMvJnLQVdeMcIBTr9ghfd/nX1AFov4Ym/jUyIm6b8mFb69jpOvJCbPKQQrxArW9BOSIVBDRIxiINpdWiUl2J2hDxS05qKe4FbVUmBy7/zbbseqHOMxnKIv/KIItAGHutLF2xvISuex/kkNaZ9IJOMXQAU/VS2rjoCwNVtMqCtIlkaXXYZpwCRjkCZga5t/vt/o3w5I4EYA7/uEOxbvq6yHDE5hX3BHvzIMg2nLlEJG4iy/9Hjrw9hPaT0zoHquTI4CmDlpYcb82FTJ+A8TgYxhPByQo8Ds3n1nOf/RPF38EgIllQxKEWr+y4pXkyg7HydGEUHgHwm9LHusBBWJSogQ0XKXDrbKaoGhwvKUfdLSRunvnMPpUilVapwlJHdNm++GSEDeb44STL1viHuh/9U5jFontZhEXB+Hi4JKJIHDlRCHE5LX7rpAGz8nD4u67vvQm3zZF08y/iVXbMJm1/eiqggzdn9JobsjPnOe2dwm9Mf8AvmqpALmnTrrhg="
  # Releases are generated automatically, stop infinite build loop
  except:
    - /^[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo /bin/bash ./bin/ci/init-db.sh
  # Run HTTPBin locally
  - docker pull citizenstig/httpbin:latest
  - docker run -d -p 80:8000 --name httpbin citizenstig/httpbin:latest
before_script:
  # Extract project name and version from mix.exs
  - source ./bin/ci/release/fetch-project-environment.sh
  # Load information about new version
  - source ./bin/ci/release/fetch-source-version.sh
  # Load information about changelog
  - source ./bin/ci/release/fetch-changelog.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/release/put-source-version.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo -a
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/ci/release/build-container.sh
  # Initialize DB for Docker container
  - source .env; PGPASSWORD="${DB_PASSWORD}"; psql -U ${DB_USER} -w -c"CREATE DATABASE ${DB_NAME}"
  # Run Docker container
  - sudo ./bin/ci/release/start-container.sh -a '--add-host=httpbin.org:$HOST_IP'
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "2" ]; then
      echo "[E] Container is not started\!";
      docker logs annon_api --details --since 5h;
      exit 1;
    fi;
  # Run acceptance tests on Docker container
  - ./test/sanity-test.sh
after_failure:
  - docker logs httpbin --details --since 5h
  - docker logs annon_api --details --since 5h
after_success:
  # Rebuild docs
  - "mix docs --output docs"
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/release/push-changes.sh
