language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.2
otp_release:
  - 19.3
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    # Docker credentials
    - secure: "jT3fV9i5qISqpcRDlSJHpOOnpxvZmAFK7RzfNRBwiZjU4SY3/2XMbZFemv3HRRirDsDyaNlHoycO4KHZKM6/04Lev82C+wX8LsNvzHAi52Yd5Eh133R2U4aI90fPy9VX6BowdjMB4nnLsW3hksWEFoSDdhzRKlCVljmDyjrmyiTvcedI76WtxILDJ9OWYtRizEVbdjmLHmIXv8vNOA5FDUfNOuHn+GhKJUUwXlyMjvzEwz1AheC2cUeS4Hgc96U01owe13AYLHItsQNQas8k1AFGRu0LmDDop5fiUgBBPTmVGvQLUO3otungigs9MsqgKT+39pCRJHirSF9dReAQXQe5xXFkhbKHXdTuLn3Uc+TeAJPiZ7PCLCmGGalZjEkKTXnhJ1vkh0+tAI1wZOC04rjPTz0AEU53spgwktklPHzOAqBDsoK+dDNzoTvlFvVGcK23UiGuMUIiyuABFdAZ9/rRgbn3uBttzT6vpRHFU5T5CPeHvpzTAjpJGn1QztJPvHySVMtcWlb9arq7xVC/mLx9xHS3WweAqvMY4RHAMeRMoxmPBeEO5DlMhOvKkfmD2p+O4v/MsM723FzrwC4Z2dN2QCq2vjfnFtDizey0ML5qJmVYxUVMCSFylKkYbdiZ5RNxKme5rCI/RVz6Vz9EPGW/NL0nDCGdvMiI11gFt+M="
    - secure: "c+YTCePFTx+g+oy+EPrSYqYox37jCGQpAfqe43NolDCBr2O6mTxBJoIc7ajEmT91oFjCSHQ8Xd3CUrKOoq7FTyXcu/8KLF4u8Ib11jYgEDKpJBLA35Hd1uMHngYv8T/aGNhpHVCr/lQq0j2TeSw+hj0CtOwXGKGiOwQL5zyVDCNinhGquIDnQ3nRFeX7fiH3yIPyfjLsibgEIOtqn4MEWvKg+Gfksb93mR6hfDK2wqu86wyHrTnrkea1hWT0TRGsXpqtMm8ivsUAkRUmWIz5P3DJ5wvTejuqc5LSygulYb0NIfNeS3KeN6b0oZ2hbuVSqTnKHyntVXFpA2L0chh6k/9B6kqsGoO7JuO5hhUwtXheI/bodVRpViLnI8Pc6Gan5WNSzgUaQiwleiO0tTP5V73ZDaQ36xQ5h6f3siqCQLj6xBM0IvGCX8GYnEUIMPNCgVubY6GLhlG9OxPh5kHmRTliZJnuJ+51hOuDiFpFgyIR7SpMGn6HJJcbCIgKc+pdKzNwBn4evlOULeG2LPUTb9MK4VRVHcoWpY5USlfv5yiPU1GAj7kVym6nbQfeLixpD/lmGnoLfyZ3T0r9+287DDP07l8oQAknmPybixkUodV7GtJ3q28RhonOTpTdaTXKjEa83+BtCLXF9nOq4hgCJBzrYcijnuFvfMl6Hzznkp0="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo /bin/bash ./bin/ci/init-db.sh
before_script:
  - epmd -daemon
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Install dependencies
  # - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo -a
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - source .env; PGPASSWORD="${DB_PASSWORD}"; psql -U ${DB_USER} -w -c"CREATE DATABASE ${DB_NAME}"
  # Run Docker container
  - sudo ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
      echo "[E] Container is not started\!";
      docker logs annon_api --details --since 5h;
      exit 1;
    fi;
  # Run acceptance tests on Docker container
  - sudo /bin/bash ./bin/ci/sanity_test.sh
  # Rebuild docs
  - "mix docs --output docs"
after_failure:
  - docker logs annon_api --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
